baseURL: https://jifan.tech
languageCode: en-us
title: Jifan's Blog
theme: ["PaperMod"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
hasCJKLanguage: true
paginate: 10
# googleAnalytics: UA-123-45
disableKinds:
  - taxonomy
  - term

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Jifan's Blog - https://jifan.tech"
  author: Jifan

  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme

  # ShowShareButtons: true
  # ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  # ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  profileMode:
    enabled: true
    title: "Hi there ðŸ‘‹" # optional default will be site title
    subtitle: "Welcome to Jifan's Blog."
    imageUrl: "/imgs/profile_hd.jpg" # optional
    # imageUrl: "https://imgur.com/1Bj50Da"
    # imageUrl: "https://sm.ms/image/EM7CePnjkS53Kvf"
    # imageTitle: "<title of image as alt>" # optional
    imageWidth: 160 # custom size
    imageHeight: 160 # custom size

  # Parameters for the search page (based on https://fusejs.io/api/options.html)
  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   distance: 1000
  #   threshold: 0.0
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]
  
  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/Fang-Lansheng/"
    - name: "Email"
      url: "mailto:jfzhang@stu.pku.edu.cn"
    - name: RSS
      url: "index.xml"

  assets:
    favicon: "/imgs/favicon.ico"
    favicon16x16:  "/imgs/favicon-16x16.png"
    favicon32x32:  "/imgs/favicon-32x32.png"
    apple_touch_icon:  "/imgs/apple-touch-icon.png"
    safari_pinned_tab:  "/imgs/safari-pinned-tab.svg"
    # disableHLJS: true

menu:
  main:
    - name: About
      url: about/
      weight: 10
    - name: Posts
      url: posts/
      weight: 20
    - name: Projects
      url: projects/
      weight: 30
    # - name: Search
    #   url: search/
    #   weight: 40
    # - name: Tags
    #   url: tags/
    #   weight: 10

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    # noClasses: false
    # style: monokai
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary